### ISSUE TITLE
Out-of-band-token can not be used with non-challenge-response tokens at the same time

### ISSUE THREAD

**Issue by jp-hoehmann** [privacyidea/privacyidea-owncloud-app#74] opened 2019-09-03 16:29 UTC
If a user has both a PUSH-token and an OTP-based token, the OTP cannot be used to sign in to OwnCloud, since a user with a PUSH -token will not be given a chance to enter an OTP.

Edit:
This will only affect tokens that cannot be used as challenge-response tokens.

**Comment by cornelinux** [comment] 2019-09-03 22:29
So you mean there is no OTP entry field, if the user has a push token?
I think this was a design decision for the first push implemention: If you really want to do push, then do push.

As bug is something that "needs to be fixed", since it hinders user from working as expected, I am changing this to enhancement.

**Comment by Mipronimo** [comment] 2019-09-04 06:11
If your OTP token is marked as a challenge response token, then both should be displayed.
If not, the ownCloud app does not know, that the user has an OTP token

**Comment by jp-hoehmann** [comment] 2019-09-10 15:21
@Mipronimo what about tokens that are not challenge-response? Do we want to support them here? I think it is rather unintuitive, that rolling out a new token can break another, that was working before. But I have no idea how much of a concern that is in practice.

**Comment by Mipronimo** [comment] 2019-09-11 17:29
There is the policy `authentication -> challenge_response`, in which you can enter a space separated list, which contains all the tokens, you want to use as challenge response tokens.
So every token, which is in this list, will be in the response of the trigger challenge.

Example:
If you want to use PUSH, TOTP and HOTP, you can enter there "totp hotp" (PUSH is not needed, cause it is always a challenge response token). If you now call the trigger challenge endpoint for a user, who has one or more tokens of these token types, all of them will appear in the response.

I hope, you understand what I try to say :D

**Comment by cornelinux** [comment] 2019-09-12 05:36
@nuvandapv Please lets talk about this in person. I think there is a misunderstanding.

**Comment by Mipronimo** [comment] 2019-09-12 14:29
Okay you'll have a problem, if you want to use e.g. PUSH and TAN-list.

So you could either add a config to ownCloud like "show allways OTP field" or you use the endpoint `/token/?user=<username>`. But then you should add a note, that the service account needs the right to do so.

**Comment by jp-hoehmann** [comment] 2019-09-12 14:46
Removing the milestone, since this probably affects roughly zero users.

**Comment by cornelinux** [comment] 2020-01-21 13:46
Again I think the headline of this issue is misleading. Otherwise this is fixed in the current devel branch.
I can use Push, HOTP, TOTP and e.g. U2F tokens. All at once.
@NuvandaPV Can we verify this?

**Comment by Mipronimo** [comment] 2020-01-21 14:25
The problem was, if you would have a PUSH token and e.g. a SPASS token (nobody should do this, but this is still possible :D), it won't work, because you cannot use a SPASS with a trigger challenge

**Comment by cornelinux** [comment] 2020-01-21 14:40
I.e. the problem is that challenge/response-token can not be used at the same time with non-C/R tokens. Hm, this is obvious.
Thanks for the clarification!

@NuvandaPV I suggest we change the topic to "C/R token with triggerchallenge can not be used with non-C/R tokens at the same time" and we close this issue.

**Comment by jp-hoehmann** [comment] 2020-01-21 22:17
@cornelinux I have modified the title you suggested slightly, since iirc this only happens for challenge-response tokens that do not require an OTP to be entered (i.e. out-of-band).

PS: Sorry for the erroneous title changes, i figured I could just get this done on my phone, but in retrospect, I probably should have picked up a notebook.

**Closed as completed** 2020-01-21 22:19 UTC
Labels: Type: Enhancement
